### ISSUE TITLE
 Could not initialize Adobe Analytics (Is Adobe Core extension enabled?)

### ISSUE THREAD

**Issue by aviemore** [adobe/react-native-acpcore#81]
Probably more like question

````javascript

      ACPCore.extensionVersion().then(version =>
        console.log('AdobeExperienceSDK: ACPCore version: ' + version),
      ); // AdobeExperienceSDK: ACPCore version: 1.5.5-R
      ACPCore.setLogLevel(ACPMobileLogLevel.VERBOSE);

      ACPAnalytics.registerExtension();
      ACPAnalytics.extensionVersion().then(version =>
        console.log('AdobeExperienceSDK: ACPAnalytics version: ' + version),
      ); AdobeExperienceSDK: ACPAnalytics version: 1.2.4

      await ACPCore.configureWithAppId(config.ADOBE_LAUNCH_ID);
      ACPCore.start();
````

Logcat `E/Analytics: Could not initialize Adobe Analytics (Is Adobe Core extension enabled?)`

What might be issue here?

**Comment by nporter-adbe** [comment]
Hi @aviemore this is probably caused by not registering other extensions such as Lifecycle, Identity, etc. I would recommend following the documentation suggestions and initialize the SDK via native code and not within Javascript.

https://github.com/adobe/react-native-acpcore#initializing
https://github.com/adobe/react-native-acpcore/blob/master/sample/ACPCoreSample/ios/ACPCoreSample/AppDelegate.m
https://github.com/adobe/react-native-acpcore/blob/master/sample/ACPCoreSample/android/app/src/main/java/com/acpcoresample/MainApplication.java
